# Site settings
title: Karl M. Davis
email: karl@justdavis.com
description: > # this means to ignore newlines until "baseurl:"
  Personal site for Karl M. Davis
baseurl: "/karl" # the subpath of your site, e.g. /blog/
url: "https://justdavis.com" # the base hostname & protocol for your site
twitter_username: karlmdavis
github_username:  karlmdavis

# Default URLs for posts.
# Options:
# 1. No trailing slash or extension: The Apache `Multiviews` option must be
#    enabled.
# 2. No trailing extension, but ends in a slash: Jekyll will render all posts
#    into subdirectories with `index.html` files.
# 3. Trailing extension (`:output_ext`): URLs will end in, for example,
#    `.html`.
permalink: /blog/:year/:title

# Build settings
markdown: kramdown
highlighter: rouge

# Specify the not-a-blog collections that are also present in this site.
# See docs: http://jekyllrb.com/docs/collections/
collections:
  it_docs:
    output: true
    permalink: /it/:path/

# Configuration for jekyll-assets.
assets:
  debug: false
  js_compressor:  uglifier
  css_compressor: sass
  assets:
    - "*.png"
    - "*.jpg"
    - "*.svg"

# Exclude some directories and files.
exclude:
  - Gemfile
  - Gemfile.lock
  - dev
  - .asset-cache   # Prevents endless looping.
  - .sass-cache    # Prevents endless looping.

gems:
  - jekyll-assets
